apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-appset
spec:
  generators:
    - list:
        elements:
          - server: in-cluster
            appns: sample-app
  template:
    metadata:
      name: sample-app
      labels:
        app: sample-app
    spec:
      project: default
      source:
        repoURL: https://github.com/ferchdav/argocd-sync.git
        targetRevision: main
        path: 10_appset
      destination:
        name: '{{server}}'
        namespace: '{{appns}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        # retry:
        #   limit: 3
        #   backoff: 
        #     duration: 5s
        #     factor: 2
        #     maxDuration: 1m
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
