apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-restart-hook-poc-5
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
    # - resources-finalizer.argocd.argoproj.io/foreground
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://github.com/ferchdav/argocd-sync.git
    targetRevision: main
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
