apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helloweb-nodeport-service
  labels:
    app: hello
spec:
  type: NodePort
  selector:
    app: hello
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: helloweb
#   labels:
#     app: hello
# spec:
#   selector:
#     matchLabels:
#       app: hello
#       tier: web
#   template:
#     metadata:
#       labels:
#         app: hello
#         tier: web
#     spec:
#       containers:
#       - name: hello-app
#         image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
#         ports:
#         - containerPort: 8080
#         resources:
#           requests:
#             cpu: 200m