---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: db
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
  template:
    metadata:
      labels:
        tier: db
    spec:
      containers:
        - name: main
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: db
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  selector:
    tier: db
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
