---
apiVersion: batch/v1
kind: Job
metadata:
  name: tests-e2e-job-jenkins
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: tests-e2e-job-jenkins
          image: ubuntu  
          command: 
            - /bin/bash
            - -c
            - |
              echo "Running in Post-Sync"
              apt-get update && apt-get install -y curl
              curl -V
      restartPolicy: Never
