---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: ui
  template:
    metadata:
      labels:
        tier: ui
    spec:
      containers:
        - name: main
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    tier: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
