apiVersion: v1
kind: Service
metadata:
  name: configmaps-example-svc
spec:
  type: NodePort
  selector:
    app: configmaps-example
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 90
      nodePort: 30777
