apiVersion: v1
kind: Service
metadata:
  name: configmaps-example-active
spec:
  type: NodePort
  selector:
    app: configmaps-example
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 100
      nodePort: 30888

