apiVersion: v1
kind: Service
metadata:
  name: configmaps-example-preview
spec:
  type: NodePort
  selector:
    app: configmaps-example
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 101
      nodePort: 30889

