kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-active
spec:
  type: NodePort
  selector:
    app: rollout-bluegreen-demo
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 90
      nodePort: 30666     # 53536
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-preview
spec:
  type: NodePort
  selector:
    app: rollout-bluegreen-demo
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 91
      nodePort: 30667     # 53548
